### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by avocat00** [albertZubov/cat-energy#6]
- Размытые иконки `.advantage__list`;
- Заливка логотипа академии;
- Наведение на неактивный элемент (пункт меню);
- Смещение элементов форм при взаимодействии; 
- Смещение при наведении `.selection-program__item-link`;
- Стили на мобиле `.selection-program__link`;
- Реализация `.example__result`;
- Реализация полоски в заголовках;
- Каталог без отрицательных отступов;
- Убрать каталог `css` из `source`;
- Реализация `nojs`;
- Реализация блока `.example`;

**Comment by albertZubov** [comment]
- Размытые иконки .advantage__list - поправил.
- Заливка логотипа академии - поправил.
- Наведение на неактивный элемент (пункт меню) - поправил.
- Смещение элементов форм при взаимодействии - поправил.
- Смещение при наведении .selection-program__item-link - поправил.
- Стили на мобиле .selection-program__link - поправил.
- Реализация nojs - поправил.
